admitted = [
    {'NAME': 'Harry Potter',
     'ADDRESS': '4 Privet Drive, Little Whinging',
     'INTERESTS': 'Quidditch, Defense Against the Dark Arts'},
    {'NAME': 'Ron Weasley',
     'ADDRESS': 'The Burrow, Ottery St Catchpole',
     'INTERESTS': 'Chess, Quidditch'},
    {'NAME': 'Hermione Granger',
     'ADDRESS': 'Hampstead, London',
     'INTERESTS': 'Reading, Spells'},
    {'NAME': 'Draco Malfoy',
     'ADDRESS': 'Malfoy Manor, Wiltshire',
     'INTERESTS': 'Quidditch, Dark Arts'},
    {'NAME': 'Luna Lovegood',
     'ADDRESS': 'The Rookery, Ottery St Catchpole',
     'INTERESTS': 'Creatures, Quibbler'},
    {'NAME': 'Neville Longbottom',
     'ADDRESS': '12 Grimmauld Place, London',
     'INTERESTS': 'Herbology, Magical Creatures'},
    {'NAME': 'Ginny Weasley',
     'ADDRESS': 'The Burrow, Ottery St Catchpole',
     'INTERESTS': 'Quidditch, Hexes'},
    {'NAME': 'Elara Moon',
     'ADDRESS': '11 Crescent Lane, Canterbury',
     'INTERESTS': 'Astronomy, Potions'}
]
